### ISSUE TITLE
running with -a and a large list of accessions (5077) doesn't work

### ISSUE THREAD

**Issue by saulakravitz** [mitre/fusera#114]
fusera mount -a PublicAccessAccessions5077.txt ./fusemnt &
[PublicAccessAccessions5077.txt](https://github.com/mitre/fusera/files/2142309/PublicAccessAccessions5077.txt)

time ~/bin/fusera.sh mount -a PublicAccessAccessions5077.txt  ~/fusemnt_all
waiting for /home/ubuntu/fusemnt_all/.initialized
/home/ubuntu/fusemnt_all initialized!

real	0m31.031s
user	0m0.000s
sys	0m0.004s
ubuntu@ip-172-31-43-159:~$ ls -lR fusemnt_all
fusemnt_all:
total 0

**Comment by mattrbianchi** [comment]
Seems like the magic number is 5019 accessions that causes fusera to have its subfolders "disappear". This is a very odd bug, as fusera does not seem to experience any errors, but after it mounts the system cannot see any of the inodes created to represent directories. What is even more odd is that the system can still read the file inode in the root directory, `.initialized`.

**Comment by mattrbianchi** [comment]
This was an issue with thinking the API could handle a large amount of accessions at a time if we weren't asking it to create signed urls. This ends up not being the case and the API will crash/reject a request with about 5k accessions. Fusera now limits a single call to the API to 2k accessions and just makes batch requests when the user wants more than 2k accessions.
