### ISSUE TITLE
Add details of what data are available via fusera to documentation?

### ISSUE THREAD

**Issue by seandavi** [mitre/fusera#130]
I probably missed it in the documentation, but what SRA subsets are available? That is, what accessions are available? Finally, what would be the incantation to mount **all** available SRA accessions?

**Comment by saulakravitz** [comment]
Sorry for the long delay.   The data available via SRA/SDDP/fusera and via the SRA/SRA-toolkit are largely disjoint.   In other words, the SDDP/fusera data is not present in the SRA, and SRA data is not present in SDDP.     This is likely to change over time as the SRA data moves to the cloud.
