### ISSUE TITLE
sracp 0.0.15 segmentation violation

### ISSUE THREAD

**Issue by saulakravitz** [mitre/fusera#134]
From:   Kochergin, Andrey (NIH/NLM/NCBI) [C] <andrey.kochergin@nih.gov>

Hi,
 
Does sracp relies on fusemount and fuse?
What would be the correct usage of sracp 0.0.15.?
 
I am getting error
“
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x93f6c1]
 
goroutine 1 [running]:
github.com/mitre/fusera/sracp/cmd.glob..func1(0xf9d0e0, 0xc000168410, 0x1, 0xd, 0x0, 0x0)
        /home/travis/gopath/src/github.com/mitre/fusera/sracp/cmd/root.go:140 +0x181
github.com/mitre/fusera/vendor/github.com/spf13/cobra.(*Command).execute(0xf9d0e0, 0xc00001e0f0, 0xd, 0xd, 0xf9d0e0, 0xc00001e0f0)
        /home/travis/gopath/src/github.com/mitre/fusera/vendor/github.com/spf13/cobra/command.go:762 +0x473
github.com/mitre/fusera/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xf9d0e0, 0x9, 0x9, 0xc00019bf78)
        /home/travis/gopath/src/github.com/mitre/fusera/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/mitre/fusera/vendor/github.com/spf13/cobra.(*Command).Execute(0xf9d0e0, 0x5, 0xc000070001)
        /home/travis/gopath/src/github.com/mitre/fusera/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/mitre/fusera/sracp/cmd.Execute()
        /home/travis/gopath/src/github.com/mitre/fusera/sracp/cmd/root.go:269 +0x2d
main.main()
        /home/travis/gopath/src/github.com/mitre/fusera/sracp/main.go:33 +0x25
”
in all possible parameter combinations I’ve tried e.g.
 
sracp -e "https://www.ncbi.nlm.nih.gov/Traces/sdl_test/1/retrieve" -t token -l gs.us -a acc.list -f vcf ./
sracp -e "https://www.ncbi.nlm.nih.gov/Traces/sdl_test/1/retrieve" -t token -l gs.us -a SRR6810109 -f vcf ./
 
, where token is a file with a jwt and acc.list is a file with 25 accessions parsed from the token
And fusera mounts just fine with the same token
 
Best regards,
-Andrey
 
https://www.ncbi.nlm.nih.gov/Traces/sdl/1/locality?acc=SRR6810109

**Comment by mattrbianchi** [comment]
Fixed in v0.0.17. Also can revert to v0.0.14.
