### ISSUE TITLE
allow_other FUSE option 

### ISSUE THREAD

**Issue by jonathonl** [mitre/fusera#147]
Setting the allow_other FUSE option in /etc/fuse.conf does not work. I'm using fusera v0.0.17 and Ubuntu v18.04.2.
```
$ ls -ahl /srv/
ls: cannot access '/srv/fusera': Permission denied
total 12K
drwxr-xr-x  4 root root 4.0K May 18 18:28 .
drwxr-xr-x 14 root root 4.0K May 18 18:09 ..
d?????????  ? ?    ?       ?            ? fusera
```

**Comment by mattrbianchi** [comment]
Hi @jonathonl, there can be a lot to dissect here. It looks like that folder is "owned" by the `root` user. It is not recommended to attempt to mount to a place owned by the `root` user. It is also not recommended to use the `allow_other` FUSE option, as listed in our wiki here: https://github.com/mitre/fusera/wiki/FUSE-and-Docker#users-and-fuse.
Finally, the `allow_other` option itself interacts with your operating system's FUSE device, not directly with Fusera. So Fusera doesn't really have a say in whether the `allow_other` option even works, it's your operating system.

**Comment by ababaian** [comment]
@mattrbianchi Given I accept the standard security warnings, how do you pass `allow_other` in fusera to fuse? 

I'm running a docker container within an EC2 instance with all my software installed, everything in the container is installed as root. As root I edited `/etc/fuse.conf` to include `user_allow_other` and when I run fusera as the user I can mount a filesystem but then can't access the data via any of software as it's all installed for root only in the container.
