### ISSUE TITLE
fusera does not account for the expiration date after the first expiration happens

### ISSUE THREAD

**Issue by hatimkhan** [mitre/fusera#73]
Wanted to report a possible bug.  After the first set of links expire, fusera does not use the new expiration date but instead keeps requesting the signed urls every time after the first expiration happens.

**Comment by john-aws** [comment]
Potentially a bug in file.go. When expired, the code calls newURL(fh.inode) and persists the retrieved link but does not appear to retrieve and persist the new expiration date back into fh.inode.Attributes.ExpirationDate.

**Comment by mattrbianchi** [comment]
Ah, thank you @hatimkhan and @john-aws, a small oversight on my part!

**Comment by mattrbianchi** [comment]
Fixed with commit f35877c
