### ISSUE TITLE
Documentation:  Room for confusion about fusera startup

### ISSUE THREAD

**Issue by saulakravitz** [mitre/fusera#94]
If fusera is started in the foreground, confusion sometimes results, since users may think it has hung.
Documentation should clearly state that fusera should be started in the background, and link to the shell script in https://github.com/mitre/fusera/wiki/Scripting-with-Fusera for an example. #

**Comment by mattrbianchi** [comment]
Achieved with 69af55e9332ae2c6c5762a48dd2d97398ab2c1f7 for now.
